### ISSUE TITLE
Text-generation-inference (TPU) container fixes

### ISSUE THREAD

**Issue by Michellehbn** [huggingface/optimum-tpu#65]
As part of the support of TPU in Inference Endpoints and for a better user experience: 

-  Resolve hanging on the server side
-  Very small generation length 

cc @tengomucho @mfuntowicz

**Comment by tengomucho** [comment]
This can be separated in several smaller tasks. I'll list them here to follow up progress.

- [ ] "warmup" fails. This is because it tries to do prefill with a very long sequence (ignoring truncate info in the request), and apparently that ends up in a RESOURCE_EXHAUSTED error.
- [x] if "health" is called before any prefill call, it hangs.
- [ ] I believe "warmup" isn't really doing anything to make prefill/decode smoother afterwards in TPU, and it's just taking time compiling and making the inference, filling TPU memory uselessly. We might consider better handling warmup calls.
- [ ] sequence length and parameters are low. We should investigate if we could increase this by bucketing or what is causing this issue. 

I have now fixed the health issue. The problem was a wrong CachedBatch serialization. progrss is in branch [debug-tgi-ie](https://github.com/huggingface/optimum-tpu/tree/debug-tgi-ie).

**Comment by tengomucho** [comment]
Daily update : warmup now works on the branch and the truncate works too. I am currently working on increasing the input length, trying to do that by bucketing prefilled inputs.

**Comment by tengomucho** [comment]
I have almost fixed everything, I do truncate as it should and I do bucketing and warmup. But I also introduced a bug, because I padded wrongly when bucketing prefills. I will fix that tomorrow.

**Comment by tengomucho** [comment]
Fixes are in https://github.com/huggingface/optimum-tpu/pull/67 https://github.com/huggingface/optimum-tpu/pull/68 and https://github.com/huggingface/optimum-tpu/pull/69. Closing this!
